# Main paths
data_path: "/home/arthur/xray_ml/pxrd_sim/src/pxrd_simulator/clin_test"
annotation_path: "/home/arthur/xray_ml/pxrd_sim/src/pxrd_simulator/clin_test"
#/home/arthur/xray_ml/real_csd_data/real_csd/
#"/home/arthur/xray_ml/pxrd_sim/src/pxrd_simulator/clin_test"
# Dataset configuration
annotations: "test.csv"
images: "data"

# Experiment parameters
save_path: "Experiments/test/pxrd_transformer"
test_name: "test"

# Laue group (options: romb, clin, all)
laue: "clin"

# Training configuration
trainer:
  accelerator: "auto"  # Options: auto, gpu
  devices: "auto"      # Options: auto, [0], [0,1], etc.
  # precision: 32      # Uncomment to enable 32-bit precision

# Model configuration  
model: "transformer"
unet_layers: 2
fft_layers: 2
pipeline: "xrd_transformer"  # Options: xrd_transformer, gan, unet
weights: "weights/XRDTransformer/synth+csd/model.ckpt"
enable_post2: false    # Post-processing step 2 (currently disabled)

# DataLoader settings
dataloader:
  batch_size: 2
  num_workers: 8

# Dataset indexing (None for full dataset)
first_index: 
max_index: 
