# main paths
data_path: "CLIN_PDB"
annotation_path: "CLIN_PDB"
exp_path: "Experiments"

# train
annotations: "train.csv"
images: "clin_1.5_0.8_60k"

# validation
val_annotations: "val.csv"
val_images: "clin_1.5_0.8_60k"

# exp params
exp_name: superformer_try7777
project: try7777

#laue params: romb, clin, all
laue: 'clin'

trainer:
  #precision: 32
  #sync_batchnorm: True
  #gradient_clip_val: 1.0
  log_every_n_steps: 20
  max_epochs: 50
  num_sanity_val_steps: 0
  accelerator: auto
  #  accelerator: gpu
  devices: auto
  #  devices: [0]
  
weights: 

model:

dataloader:
  batch_size: 32
  num_workers: 8

optimizer: adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0001

scheduler: plateau
scheduler_params:
  patience: 5
  factor: 0.1
  verbose: True
  target_metric: Loss/val
  mode: min

checkpoint:
  monitor: Loss/val
  filename: model
  mode: min

