# main paths
data_path: "/home/jupyter/datasphere/datasets/mono_500k/clin_1.5_0.8_500k"
annotation_path: "/home/jupyter/datasphere/datasets/mono_500k/clin_1.5_0.8_500k"
exp_path: "Experiments"

# train
annotations: "train.csv"
images: "data"

# validation
val_annotations: "val.csv"
val_images: "data"

# exp params
exp_name: 'try06_11'
project: 'XRDTransformer'

#laue params: romb, clin, all
laue: 'clin'
pipeline: 'xrd_transformer'
trainer:
  precision: "16-mixed"
  #sync_batchnorm: True
  #gradient_clip_val: 1.0
  log_every_n_steps: 20
  max_epochs: 20
  num_sanity_val_steps: 0
  accelerator: auto
  #  accelerator: gpu
  devices: auto
  #  devices: [0]
  
weights: 

model:

dataloader:
  batch_size: 8
  num_workers: 16

optimizer: adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0001

scheduler: plateau
scheduler_params:
  patience: 5
  factor: 0.1
  verbose: True
  target_metric: Loss/val
  mode: min

checkpoint:
  monitor: Loss/val
  filename: model
  mode: min

