# Data Paths
data_path: 'xrd_datasets/toy_csd'
annotation_path: 'xrd_datasets/toy_csd'
exp_path: "experiments"

# Training Data
annotations: "train.csv"
images: "data"

# Validation Data  
val_annotations: "val.csv"
val_images: "data"

# Experiment Configuration
exp_name: 'toy_csd'
project: 'toy_train'
laue: 'clin'                # Options: romb, clin, all
pipeline: 'unet'             # Options: xrd_transformer, gan, unet (for fft too)

# Training Parameters
trainer:
  log_every_n_steps: 1
  max_epochs: 100
  num_sanity_val_steps: 1
  accelerator: auto         # Options: auto, gpu
  devices: auto            # Options: auto, [0], [0,1], etc.
  # precision: "16-mixed"  
  # sync_batchnorm: True
  # gradient_clip_val: 1.0

# Model Configuration
weights: 
model: 'fft'
unet_layers: 2
fft_layers: 2

# DataLoader Settings
dataloader:
  batch_size: 100
  num_workers: 12

# Optimizer Configuration
optimizer: adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0001

# Learning Rate Scheduler
scheduler: plateau
scheduler_params:
  patience: 2
  factor: 0.5
  verbose: True
  target_metric: Loss/val   # Use g_loss/val for GAN, Loss/val for other pipelines
  mode: min

# Checkpoint Configuration  
checkpoint:
  monitor: Loss/val
  filename: model
  mode: min

# Dataset indexing (None for full dataset)
first_index: 
max_index: 
