name: Monitor Changes and Send Notifications

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get commit details
      id: commit
      run: |
        echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
        echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
        echo "files_changed=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Send Telegram Notification
      if: contains(steps.commit.outputs.message, 'Auto commit:')
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          🔄 Новый автоматический коммит обнаружен!
          
          Сообщение коммита: ${{ steps.commit.outputs.message }}
          
          Измененные файлы:
          ${{ steps.commit.outputs.files_changed }}
          
          Репозиторий: ${{ github.repository }}
          Ссылка: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
