name: Check for changes and commit to target repo

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать ежедневно в 00:00 UTC
  workflow_dispatch:  # Возможность вручную запустить workflow

jobs:
  detect-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout homework repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Полный fetch для работы с изменениями

    - name: Set up the target repository (autocommit repository)
      uses: actions/checkout@v3
      with:
        repository: blackwood168/xrd_phase_ml  # Замените на имя вашего репозитория для автокоммитов

    - name: Check for changes in target repo
      id: check-changes
      run: |

        # Получаем изменения из main ветки репозитория для автокоммитов
        git fetch origin main

        # Проверяем изменения в репозитории (проверка только на небольшие файлы < 150 MB)
        git diff --name-only origin/main > changes.txt

        # Фильтруем файлы, размер которых меньше 150 МБ
        awk '{
          "du -b " $1 "| awk \047{if ($1 < 150000000) print $0}\047" | getline size;
          if (size != "") print $1
        }' changes.txt > small_changes.txt

        if [ -s small_changes.txt ]; then
          echo "::set-output name=has_changes::true"
        else
          echo "::set-output name=has_changes::false"
        fi

    - name: Commit changes to target repo
      if: ${{ steps.check-changes.outputs.has_changes == 'true' }}
      run: |
        # Переходим в ветку uncom_update или создаем её, если ее нет
        git checkout -b uncom_update || git checkout uncom_update

        # Добавляем изменения
        git add $(cat small_changes.txt)
        git commit -m "Automated commit: $(date '+%Y-%m-%d')"
        git push origin uncom_update

    - name: Notify via Telegram
      if: ${{ steps.check-changes.outputs.has_changes == 'true' }}
      run: |
        curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "✅ Changes detected and committed to uncom_update branch in target-repo."}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
